Ticketsalesman Search/Make/Remove tickets
Sybrendj2001/Cinema pull request #19
Opened 2020-04-03 17:21 UTC by jjtc19

2020-04-04 15:49 UTC, timfeskens requested changes
kleine notes + wat ik met je via app besproken heb :p

2020-04-04 15:49 UTC, timfeskens commented on CinemaConsole/Program.cs
> +                        //TicketInfo goIntoTicket = new TicketInfo("Sybren",3,3,13.00,"17/02/2020 16:30","Thor",2);
Comment vergeten weg te halen?

2020-04-04 15:49 UTC, timfeskens commented on CinemaConsole/Pages/TicketSalesman.cs
> +        public static void Tickets()
Even een summary wat de functie doet ;)

2020-04-04 15:49 UTC, timfeskens commented on CinemaConsole/Pages/Customer.cs
> +        public static void Overview(TicketInfo ticket)
Even een summary wat de functie doet ;)

2020-04-04 15:49 UTC, timfeskens commented on CinemaConsole/Data/BackEnd/TicketInfo.cs
> +
extra entertjes weghalen pls

2020-04-06 11:30 UTC, timfeskens approved these changes
toppppp

2020-04-06 11:33 UTC, markhof010 approved these changes

2020-04-06 11:33 UTC, merged