Checks
Sybrendj2001/Cinema pull request #39
Opened 2020-05-12 13:37 UTC by Sybrendj2001

In admin i changed addtime and edittime. Also i fixed the namespace for customer and added duration and genre for the movies

2020-05-12 13:47 UTC, timfeskens requested changes
>:(

2020-05-12 13:47 UTC, timfeskens commented on CinemaConsole/Pages/Admin/Admin.cs
> +
remove whitespace

2020-05-12 13:47 UTC, timfeskens commented on CinemaConsole/Pages/Admin/Admin.cs
> +                                //TODO: Add add catch
add a catch

2020-05-12 13:47 UTC, timfeskens commented on CinemaConsole/Pages/Admin/Admin.cs
> +
remove whiteline

2020-05-20 11:10 UTC, jjtc19 approved these changes

2020-05-20 12:56 UTC, timfeskens commented
closed instead of merged

2020-05-20 12:56 UTC, timfeskens approved these changes

2020-05-20 12:57 UTC, merged